'use client';

import { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, RefreshCw, ShieldCheck } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AppShell } from '@/components/layout/app-shell';
import { useLocale } from '@/components/i18n/locale-provider';
import { localize } from '@/lib/i18n';

export type AdminResource = 'users' | 'patients' | 'doctors' | 'facilities' | 'tests' | 'agents' | 'appointments' | 'reports';
type Props = { resource: AdminResource; title: string; description: string; columns: string[] };

const labels: Record<string, string> = { users: 'Users', patients: 'Patients', doctors: 'Doctors', facilities: 'Facilities', tests: 'Tests', agents: 'Collection agents', appointments: 'Appointments', reports: 'Medical reports' };
function display(value: unknown) { if (value === null || value === undefined || value === '') return '—'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; if (typeof value === 'string' && (value.includes('T') || value.endsWith('Z'))) return new Date(value).toLocaleString(); return String(value); }

export function AdminHeader({ title, description }: { title: string; description: string }) { const { locale } = useLocale(); return <div className="mb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-[#0d766c]">{localize(locale, 'Platform operations')}</p><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">{localize(locale, title)}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#718988]">{localize(locale, description)}</p></div>; }
export function AdminGuard({ children }: { children: React.ReactNode }) { return <AppShell>{children}</AppShell>; }

export function AdminResourcePage({ resource, title, description, columns }: Props) { const { locale } = useLocale(); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); async function load() { setLoading(true); const response = await fetch(`/api/admin/${resource}`); const payload = await response.json().catch(() => ({})); if (response.ok) setRows(payload.rows ?? []); else setError(payload.error ?? 'Could not load records.'); setLoading(false); } useEffect(() => { void load(); }, [resource]); async function action(id: string, actionName: string) { setMessage(null); const response = await fetch(`/api/admin/${resource}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, action: actionName }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error ?? 'Action failed.'); else { setMessage('Change saved.'); await load(); } }
  return <AdminGuard><AdminHeader title={title} description={description} /><div className="mb-4 flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8ba19f]">{localize(locale, labels[resource])} · {rows.length} shown</p><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw size={14} className={loading ? 'animate-spin' : ''} />{localize(locale, 'Refresh')}</Button></div>{error && <Card className="mb-4 border-[#f2d4d4] bg-[#fff8f8] p-4 text-sm text-[#a84e58]"><CircleAlert className="mr-2 inline" size={16} />{localize(locale, error)}</Card>}{message && <Card className="mb-4 border-[#dce9e8] bg-[#f3faf7] p-4 text-sm text-[#0d766c]"><CheckCircle2 className="mr-2 inline" size={16} />{localize(locale, message)}</Card>}{loading ? <Card className="p-8 text-sm text-[#718988]">{localize(locale, 'Loading records…')}</Card> : rows.length ? <div className="overflow-x-auto rounded-2xl border border-[#dce9e8] bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-[#e8f0ef] bg-[#f8fbfa]"><tr>{columns.map((column) => <th key={column} className="px-5 py-4 text-[10px] font-bold uppercase tracking-[.12em] text-[#8ba19f]">{column.replaceAll('_', ' ')}</th>)}<th className="px-5 py-4 text-[10px] font-bold uppercase tracking-[.12em] text-[#8ba19f]">{localize(locale, 'Action')}</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)} className="border-b border-[#eef4f3] last:border-0"><td className="px-5 py-4 font-semibold">{display(row[columns[0]])}</td>{columns.slice(1).map((column) => <td key={column} className="px-5 py-4 text-[#718988]">{display(row[column])}</td>)}<td className="px-5 py-4"><AdminAction resource={resource} row={row} onAction={action} /></td></tr>)}</tbody></table></div> : <Card className="border-dashed p-10 text-center"><ShieldCheck className="mx-auto text-[#0d766c]" size={22} /><h2 className="mt-3 font-bold">{localize(locale, 'No records found')}</h2><p className="mt-2 text-sm text-[#718988]">{localize(locale, `There are no ${labels[resource].toLowerCase()} available in this view.`)}</p></Card>}</AdminGuard>; }

function AdminAction({ resource, row, onAction }: { resource: AdminResource; row: Record<string, unknown>; onAction: (id: string, action: string) => void }) { const { locale } = useLocale(); const id = String(row.id); const actionMap: Record<AdminResource, { action: string; label: string } | null> = { users: row.is_verified ? { action: 'unverify', label: 'Unverify' } : { action: 'verify', label: 'Verify' }, patients: null, doctors: row.approval_status === 'APPROVED' ? { action: 'suspend', label: 'Suspend' } : { action: 'approve', label: 'Approve' }, facilities: row.is_approved ? { action: 'unapprove', label: 'Unapprove' } : { action: 'approve', label: 'Approve' }, tests: row.is_active ? { action: 'deactivate', label: 'Deactivate' } : { action: 'activate', label: 'Activate' }, agents: row.is_verified ? { action: 'unverify', label: 'Unverify' } : { action: 'verify', label: 'Verify' }, appointments: null, reports: null }; const config = actionMap[resource]; return config ? <Button size="sm" variant="outline" onClick={() => onAction(id, config.action)}>{localize(locale, config.label)}</Button> : <span className="text-xs text-[#9aafad]">{localize(locale, 'View only')}</span>; }
