'use client';

import Link from 'next/link';
import { ArrowRight, CircleAlert, LoaderCircle } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useLocale } from '@/components/i18n/locale-provider';
import { localize } from '@/lib/i18n';

export function PatientHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: { label: string; href: string } }) { const { locale } = useLocale(); return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-[#0d766c]">{localize(locale, eyebrow)}</p><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">{localize(locale, title)}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#718988]">{localize(locale, description)}</p></div>{action && <Link href={action.href}><Button variant="outline">{localize(locale, action.label)}<ArrowRight size={15} /></Button></Link>}</div>; }
export function PortalAuthState() { const { locale } = useLocale(); return <Card className="border-[#f2d4d4] bg-[#fff8f8] p-8"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 text-[#a84e58]" size={19} /><div><h2 className="font-bold">{localize(locale, 'Sign in required')}</h2><p className="mt-2 text-sm leading-6 text-[#8d696d]">{localize(locale, 'Sign in with Supabase Auth to view your private patient records.')}</p></div></div></Card>; }
export function PortalErrorState({ message = 'We could not load this section.' }: { message?: string }) { const { locale } = useLocale(); return <Card className="border-[#f2d4d4] bg-[#fff8f8] p-8"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 text-[#a84e58]" size={19} /><div><h2 className="font-bold">{localize(locale, 'Something went wrong')}</h2><p className="mt-2 text-sm leading-6 text-[#8d696d]">{localize(locale, message)}</p></div></div></Card>; }
export function PortalLoadingState() { const { locale } = useLocale(); return <Card className="flex items-center gap-3 p-8 text-sm text-[#718988]"><LoaderCircle className="animate-spin" size={18} />{localize(locale, 'Loading your records…')}</Card>; }
export function EmptyState({ title, description, href, action }: { title: string; description: string; href?: string; action?: string }) { const { locale } = useLocale(); return <Card className="border-dashed p-8 text-center"><h2 className="font-bold">{localize(locale, title)}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#718988]">{localize(locale, description)}</p>{href && action && <Link className="mt-5 inline-block" href={href}><Button variant="outline">{localize(locale, action)}<ArrowRight size={15} /></Button></Link>}</Card>; }
export function MetricCard({ label, value, detail, href }: { label: string; value: string | number; detail: string; href?: string }) { const { locale } = useLocale(); const content = <Card className="p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#8ba19f]">{localize(locale, label)}</p><p className="mt-3 text-3xl font-bold tracking-[-.04em] text-[#153238]">{value}</p><p className="mt-1 text-xs leading-5 text-[#718988]">{localize(locale, detail)}</p></Card>; return href ? <Link href={href} className="block transition-transform hover:-translate-y-0.5">{content}</Link> : content; }
export function DateLabel({ value }: { value: string | null }) { const { locale } = useLocale(); if (!value) return <span>{localize(locale, 'Not scheduled')}</span>; return <time dateTime={value}>{new Date(value).toLocaleString(locale === 'hi' ? 'hi-IN' : 'en-IN')}</time>; }
