'use client';

import { useEffect, useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

type Report = { id: string; report_title: string; report_type: string; original_filename: string; mime_type: string; file_size: number; created_at: string };

export default function PatientReportsPage() { const [reports, setReports] = useState<Report[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { void (async () => { const response = await fetch('/api/patient/reports'); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error ?? 'Could not load reports.'); else setReports(payload.reports ?? []); setLoading(false); })(); }, []); async function download(id: string) { const response = await fetch(`/api/reports/${id}/download`); const payload = await response.json(); if (response.ok && payload.downloadUrl) window.open(payload.downloadUrl, '_blank', 'noopener,noreferrer'); else setError(payload.error ?? 'Download unavailable.'); } return <AppShell><div className="mb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-[#0d766c]">Private records</p><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">Medical reports</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#718988]">View report metadata and request a short-lived signed download. Reports are never public.</p></div>{loading ? <Card className="p-8 text-sm text-[#718988]">Loading reports…</Card> : error ? <Card className="border-[#f2d4d4] bg-[#fff8f8] p-8 text-sm text-[#a84e58]">{error}</Card> : reports.length ? <div className="space-y-3">{reports.map((report) => <Card key={report.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#f4ecff] text-[#8a5ab7]"><FileText size={19} /></div><div className="min-w-0 flex-1"><h2 className="font-bold">{report.report_title}</h2><p className="mt-1 text-sm text-[#718988]">{report.report_type.replace('_', ' ')} · {report.original_filename}</p><p className="mt-1 text-xs text-[#8ba19f]">Uploaded {new Date(report.created_at).toLocaleString()} · {(report.file_size / 1024).toFixed(0)} KB</p></div><Button variant="outline" size="sm" onClick={() => void download(report.id)}><Download size={15} />Download</Button></Card>)}</div> : <Card className="border-dashed p-10 text-center"><h2 className="font-bold">No reports available</h2><p className="mt-2 text-sm text-[#718988]">Reports uploaded for your test orders will appear here.</p></Card>}</AppShell>; }
