'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowRight, ClipboardCheck, FileText, Hospital, ShieldCheck, Stethoscope, Users } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';
import { AdminHeader } from '@/components/dashboard/admin-portal';

type Metrics = { users: number; patients: number; doctors: number; facilities: number; agents: number; appointments: number; testOrders: number; pendingCollections: number; reports: number };
const cards: { key: keyof Metrics; label: string; href: string; icon: typeof Users }[] = [{ key: 'patients', label: 'Patients', href: '/admin/patients', icon: Users }, { key: 'doctors', label: 'Doctors', href: '/admin/doctors', icon: Stethoscope }, { key: 'facilities', label: 'Facilities', href: '/admin/facilities', icon: Hospital }, { key: 'agents', label: 'Collection agents', href: '/admin/agents', icon: Activity }, { key: 'appointments', label: 'Appointments', href: '/admin/appointments', icon: ClipboardCheck }, { key: 'testOrders', label: 'Test orders', href: '/admin/tests', icon: ClipboardCheck }, { key: 'pendingCollections', label: 'Pending collections', href: '/admin/agents', icon: ShieldCheck }, { key: 'reports', label: 'Medical reports', href: '/admin/reports', icon: FileText }];
export default function AdminDashboardPage() { const [metrics, setMetrics] = useState<Metrics | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { void (async () => { const response = await fetch('/api/admin/overview'); const payload = await response.json().catch(() => ({})); if (response.ok) setMetrics(payload.metrics); else setError(payload.error ?? 'Administrator access required.'); })(); }, []); return <AppShell><AdminHeader title="Platform oversight, without unrestricted browser access." description="Review operational coverage, verification queues, and healthcare records through server-authorized admin views." />{error ? <Card className="border-[#f2d4d4] bg-[#fff8f8] p-8 text-sm text-[#a84e58]">{error}</Card> : !metrics ? <Card className="p-8 text-sm text-[#718988]">Loading platform metrics…</Card> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({ key, label, href, icon: Icon }) => <Link href={href} key={key} className="block"><Card className="p-5 transition-transform hover:-translate-y-0.5"><Icon className="text-[#0d766c]" size={19} /><p className="mt-4 text-3xl font-bold">{metrics[key]}</p><p className="mt-1 text-xs text-[#718988]">{label}</p><ArrowRight className="mt-4 text-[#9aafad]" size={16} /></Card></Link>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="font-bold">Administrative controls</h2><p className="mt-3 text-sm leading-6 text-[#718988]">Use resource pages to verify platform users, approve doctors and facilities, activate tests, and verify collection agents. Role changes remain protected and are not editable from this browser workspace.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/admin/users" className="rounded-xl border border-[#dce9e8] px-4 py-2 text-sm font-semibold text-[#0d766c]">Review users</Link><Link href="/admin/doctors" className="rounded-xl border border-[#dce9e8] px-4 py-2 text-sm font-semibold text-[#0d766c]">Review doctors</Link></div></Card><Card className="p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-[#0d766c]" size={19} /><div><h2 className="font-bold">Security boundary</h2><p className="mt-3 text-sm leading-6 text-[#718988]">Every request checks Supabase Auth and the database `is_admin()` function. The browser never receives service-role credentials or unrestricted database access.</p></div></div></Card></div></>}</AppShell>; }
