'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ClipboardCheck } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';
import { AgentErrorState, AgentHeader, AgentEmptyState, LocationLine, MinimumNecessaryNotice, StatusBadge } from '@/components/dashboard/agent-portal';

type RequestItem = { id: string; status: string; scheduled_at: string; collection_city: string | null; collection_state: string | null; contact_name: string; order: { test: { name: string } | null; facility: { name: string } | null } | null };

export default function AgentRequestsPage() { const [items, setItems] = useState<RequestItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { void (async () => { const response = await fetch('/api/agent/requests'); const payload = await response.json().catch(() => ({})); if (response.ok) setItems(payload.requests ?? []); else setError(payload.error ?? 'Could not load assigned requests.'); setLoading(false); })(); }, []); return <AppShell><AgentHeader eyebrow="Field operations" title="Assigned requests" description="Review only the visits assigned to your verified agent profile." />{loading ? <Card className="p-8 text-sm text-[#718988]">Loading assigned requests…</Card> : error ? <AgentErrorState message={error} /> : items.length ? <><div className="space-y-3">{items.map((item) => <Link key={item.id} href={`/agent/requests/${item.id}`} className="block"><Card className="flex flex-col gap-4 p-5 transition-colors hover:bg-[#fbfdfc] sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#eef2ff] text-[#5865b8]"><ClipboardCheck size={19} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{item.order?.test?.name || 'Diagnostic collection'}</h2><StatusBadge status={item.status} /></div><p className="mt-2 text-sm text-[#718988]">{item.contact_name} · {new Date(item.scheduled_at).toLocaleString()}</p><p className="mt-1 text-xs text-[#8ba19f]"><LocationLine city={item.collection_city} state={item.collection_state} /> · {item.order?.facility?.name || 'Assigned facility'}</p></div><ArrowRight className="shrink-0 text-[#9aafad]" size={18} /></Card></Link>)}</div><MinimumNecessaryNotice /></> : <AgentEmptyState title="No assigned requests" description="Assigned home collection visits will appear here after an administrator assigns them." />}</AppShell>; }
