import Link from 'next/link';
import { ClipboardCheck, Clock3, Home, UserRound } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AgentAuthState, AgentEmptyState, AgentErrorState, AgentHeader, MinimumNecessaryNotice, StatusBadge } from '@/components/dashboard/agent-portal';
import { getAgentContext } from '@/lib/agent-portal';

export default async function AgentDashboardPage() {
  const { supabase, user, agent, error } = await getAgentContext();
  if (!user) return <AppShell><AgentHeader eyebrow="Field operations" title="Collection visits, clearly coordinated." description="Manage only the home sample collections assigned to you." /><AgentAuthState /></AppShell>;
  if (error) return <AppShell><AgentHeader eyebrow="Field operations" title="Collection workspace" description="Assigned visits and status updates." /><AgentErrorState /></AppShell>;
  if (!agent || !agent.is_verified) return <AppShell><AgentHeader eyebrow="Field operations" title="Verification required." description="Collection access is enabled only after platform verification." /><AgentEmptyState title="Your agent profile is not verified" description="Please wait for platform verification or contact an administrator." /></AppShell>;
  const { data: requests, error: requestError } = await supabase.from('collection_requests').select('id, status, scheduled_at, collection_city, collection_state, contact_name, test_order_id').eq('collection_agent_id', agent.id).order('scheduled_at', { ascending: true }).limit(100);
  if (requestError) return <AppShell><AgentHeader eyebrow="Field operations" title="Collection workspace" description="Assigned visits and status updates." /><AgentErrorState /></AppShell>;
  const active = (requests ?? []).filter((request) => !['DELIVERED', 'CANCELLED'].includes(request.status));
  const today = (requests ?? []).filter((request) => new Date(request.scheduled_at).toDateString() === new Date().toDateString());
  return <AppShell><AgentHeader eyebrow="Field operations" title="Ready for today’s visits." description={`Assigned to ${agent.service_area || 'your service area'}. Keep each status update timely and accurate.`} action={{ label: 'View all requests', href: '/agent/requests' }} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-5"><Clock3 className="text-[#0d766c]" size={19} /><p className="mt-4 text-3xl font-bold">{today.length}</p><p className="mt-1 text-xs text-[#718988]">Visits today</p></Card><Card className="p-5"><ClipboardCheck className="text-[#5865b8]" size={19} /><p className="mt-4 text-3xl font-bold">{active.length}</p><p className="mt-1 text-xs text-[#718988]">Active requests</p></Card><Card className="p-5"><Home className="text-[#c47643]" size={19} /><p className="mt-4 text-3xl font-bold">{(requests ?? []).length}</p><p className="mt-1 text-xs text-[#718988]">Assigned total</p></Card><Card className="p-5"><UserRound className="text-[#8a5ab7]" size={19} /><p className="mt-4 text-sm font-bold">{agent.is_available ? 'Available' : 'Unavailable'}</p><p className="mt-1 text-xs text-[#718988]">Current availability</p></Card></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8ba19f]">Next visits</p><h2 className="mt-1 text-lg font-bold">Assigned collection requests</h2></div><ClipboardCheck className="text-[#0d766c]" size={20} /></div>{active.length ? <div className="space-y-3">{active.slice(0, 5).map((request) => <Link key={request.id} href={`/agent/requests/${request.id}`} className="block rounded-xl border border-[#e8f0ef] p-4 hover:bg-[#f8fbfa]"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{request.contact_name}</p><StatusBadge status={request.status} /></div><p className="mt-2 text-sm text-[#718988]">{new Date(request.scheduled_at).toLocaleString()} · {request.collection_city || ''} {request.collection_state || ''}</p></Link>)}</div> : <AgentEmptyState title="No active assignments" description="New assigned home collection visits will appear here." />}<Link href="/agent/requests"><Button className="mt-5" variant="outline" size="sm">Open request list</Button></Link></Card><Card className="p-6"><h2 className="font-bold">Field safety and privacy</h2><p className="mt-3 text-sm leading-6 text-[#718988]">Use the request detail only for the scheduled collection. The portal does not expose diagnoses, reports, prescriptions, or unrelated patient records.</p><MinimumNecessaryNotice /></Card></div></AppShell>;
}
