'use client';

import { FormEvent, useEffect, useState } from 'react';
import { UserRound } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AgentErrorState, AgentHeader } from '@/components/dashboard/agent-portal';

type Profile = { service_area: string | null; is_available: boolean; is_verified: boolean; created_at: string };
export default function AgentProfilePage() { const [profile, setProfile] = useState<Profile | null>(null); const [serviceArea, setServiceArea] = useState(''); const [available, setAvailable] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); useEffect(() => { void (async () => { const response = await fetch('/api/agent/profile'); const payload = await response.json().catch(() => ({})); if (response.ok && payload.profile) { setProfile(payload.profile); setServiceArea(payload.profile.service_area ?? ''); setAvailable(payload.profile.is_available); } else setMessage(payload.error ?? 'Could not load profile.'); setLoading(false); })(); }, []); async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const response = await fetch('/api/agent/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceArea, isAvailable: available }) }); const payload = await response.json().catch(() => ({})); if (response.ok) { setProfile(payload.profile); setMessage('Profile saved.'); } else setMessage(payload.error ?? 'Could not save profile.'); setSaving(false); } return <AppShell><AgentHeader eyebrow="Field operations" title="Agent profile" description="Manage the service-area and availability details used for assignment." />{loading ? <Card className="p-8 text-sm text-[#718988]">Loading profile…</Card> : !profile ? <AgentErrorState message={message ?? 'No collection-agent profile is linked to this account.'} /> : <Card className="max-w-2xl p-6"><div className="mb-6 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#eef2ff] text-[#5865b8]"><UserRound size={19} /></span><div><h2 className="font-bold">Field profile</h2><p className="text-xs text-[#8ba19f]">Verification: {profile.is_verified ? 'Verified' : 'Pending administrator verification'}</p></div></div>{message && <p className="mb-4 rounded-xl bg-[#f3faf7] px-3 py-2 text-sm text-[#0d766c]">{message}</p>}<form onSubmit={save} className="space-y-4"><label className="block text-xs font-bold text-[#506a6a]">Service area<input value={serviceArea} onChange={(event) => setServiceArea(event.target.value)} maxLength={160} className="mt-2 w-full rounded-xl border border-[#dce9e8] px-3 py-3 text-sm font-normal" placeholder="City or locality" /></label><label className="flex items-center gap-3 rounded-xl border border-[#dce9e8] p-4 text-sm font-semibold text-[#506a6a]"><input type="checkbox" checked={available} onChange={(event) => setAvailable(event.target.checked)} className="h-4 w-4 accent-[#0d766c]" />Available for new assignments</label><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save profile'}</Button></form></Card>}</AppShell>; }
