export type Locale = 'en' | 'hi';
export const localeCookie = 'hc_locale';

const translations = {
  en: {
    'language.english': 'English', 'language.hindi': 'हिन्दी', 'language.label': 'Language',
    'nav.overview': 'Overview', 'nav.patient': 'Patient area', 'nav.appointments': 'Appointments', 'nav.tests': 'Test orders', 'nav.reports': 'Reports', 'nav.timeline': 'Health timeline', 'nav.consent': 'Record consent', 'nav.notifications': 'Notifications', 'nav.profile': 'Profile', 'nav.doctor': 'Doctor area', 'nav.doctorAppointments': 'Doctor appointments', 'nav.doctorPatients': 'Doctor patients', 'nav.consultations': 'Consultations', 'nav.prescriptions': 'Prescriptions', 'nav.doctorTests': 'Doctor test orders', 'nav.doctorReports': 'Doctor reports', 'nav.doctorProfile': 'Doctor profile', 'nav.agent': 'Agent area', 'nav.agentRequests': 'Agent requests', 'nav.agentProfile': 'Agent profile', 'nav.admin': 'Admin area', 'nav.adminUsers': 'Admin users', 'nav.adminPatients': 'Admin patients', 'nav.adminDoctors': 'Admin doctors', 'nav.adminFacilities': 'Admin facilities', 'nav.adminTests': 'Admin tests', 'nav.adminAgents': 'Admin agents', 'nav.adminAppointments': 'Admin appointments', 'nav.adminReports': 'Admin reports',
    'shell.applicationAreas': 'Application areas', 'shell.workspace': 'Secure care coordination workspace', 'shell.fieldOperations': 'Field operations', 'shell.fieldDescription': 'Assigned collection access is minimum-necessary', 'shell.phase': 'Phase 18', 'shell.openNavigation': 'Open navigation', 'shell.closeNavigation': 'Close navigation',
    'common.signInRequired': 'Sign in required', 'common.signInPatient': 'Sign in with Supabase Auth to view your private patient records.', 'common.somethingWrong': 'Something went wrong', 'common.loading': 'Loading your records…', 'common.notScheduled': 'Not scheduled', 'common.noRecords': 'No records found', 'common.view': 'View', 'common.refresh': 'Refresh', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.open': 'Open', 'common.back': 'Back', 'common.noData': 'No data available yet.',
    'portal.authAgentTitle': 'Agent sign-in required', 'portal.authAgentDescription': 'Sign in with a verified collection-agent account to access assigned requests.', 'portal.authAdmin': 'Administrator access required', 'portal.errorAgent': 'We could not load this collection-agent workspace.', 'portal.errorAdmin': 'We could not load this administrative workspace.', 'portal.errorPatient': 'We could not load this section.', 'portal.doctorAuth': 'Doctor sign-in required', 'portal.doctorAuthDescription': 'Sign in with an approved doctor account to access clinical workspace data.', 'portal.doctorError': 'We could not load this doctor workspace.', 'portal.minimumNecessary': 'Only collection details necessary for the assigned visit are shown. Patient medical records and unrelated requests remain private.', 'portal.locationMissing': 'Location not provided',
    'portal.noAppointments': 'No appointments yet', 'portal.noTests': 'No diagnostic tests yet', 'portal.noReports': 'No reports available yet', 'portal.findDoctor': 'Find a doctor', 'portal.browseFacilities': 'Browse facilities', 'portal.today': 'Today', 'portal.upcoming': 'Upcoming', 'portal.patients': 'Patients', 'portal.consultations': 'Consultations', 'admin.users': 'Users', 'admin.patients': 'Patients', 'admin.doctors': 'Doctors', 'admin.facilities': 'Facilities', 'admin.tests': 'Tests', 'admin.agents': 'Collection agents', 'admin.appointments': 'Appointments', 'admin.reports': 'Medical reports', 'admin.platformOperations': 'Platform operations', 'admin.action': 'Action', 'admin.loading': 'Loading records…', 'admin.noRecords': 'No records found', 'admin.viewOnly': 'View only', 'admin.verify': 'Verify', 'admin.unverify': 'Unverify', 'admin.approve': 'Approve', 'admin.suspend': 'Suspend', 'admin.unapprove': 'Unapprove', 'admin.activate': 'Activate', 'admin.deactivate': 'Deactivate',
 'ai.back': 'Back to patient area', 'ai.badge': 'HEALTH ASSISTANT', 'ai.title': 'Talk through a health concern.', 'ai.disclaimer': 'Share what you are experiencing for preliminary information and safety-oriented next steps. This is not a diagnosis and does not replace a qualified clinician.', 'ai.preliminary': 'Preliminary information only', 'ai.prompt': 'What would you like to understand?', 'ai.promptDescription': 'Describe your symptoms, how long they have been present, and anything that makes them better or worse. Avoid sharing passwords or unrelated personal information.', 'ai.reviewing': 'Reviewing your message safely…', 'ai.placeholder': 'Describe your concern…', 'ai.ariaConcern': 'Describe your health concern', 'ai.ariaSend': 'Send message', 'ai.emergencyWarning': 'Do not use this chat for emergencies.', 'ai.safetyFirst': 'Safety first', 'ai.emergencyDescription': 'For severe symptoms, call local emergency services or go to the nearest emergency department. The assistant cannot assess emergencies.', 'ai.urgent': 'Urgent next step', 'ai.suggested': 'Suggested next step',
  },
  hi: {
    'language.english': 'English', 'language.hindi': 'हिन्दी', 'language.label': 'भाषा',
    'nav.overview': 'अवलोकन', 'nav.patient': 'मरीज़ क्षेत्र', 'nav.appointments': 'अपॉइंटमेंट', 'nav.tests': 'जाँच ऑर्डर', 'nav.reports': 'रिपोर्ट', 'nav.timeline': 'स्वास्थ्य टाइमलाइन', 'nav.consent': 'रिकॉर्ड सहमति', 'nav.notifications': 'सूचनाएँ', 'nav.profile': 'प्रोफ़ाइल', 'nav.doctor': 'डॉक्टर क्षेत्र', 'nav.doctorAppointments': 'डॉक्टर अपॉइंटमेंट', 'nav.doctorPatients': 'डॉक्टर के मरीज़', 'nav.consultations': 'परामर्श', 'nav.prescriptions': 'प्रिस्क्रिप्शन', 'nav.doctorTests': 'डॉक्टर जाँच ऑर्डर', 'nav.doctorReports': 'डॉक्टर रिपोर्ट', 'nav.doctorProfile': 'डॉक्टर प्रोफ़ाइल', 'nav.agent': 'एजेंट क्षेत्र', 'nav.agentRequests': 'एजेंट अनुरोध', 'nav.agentProfile': 'एजेंट प्रोफ़ाइल', 'nav.admin': 'एडमिन क्षेत्र', 'nav.adminUsers': 'एडमिन उपयोगकर्ता', 'nav.adminPatients': 'एडमिन मरीज़', 'nav.adminDoctors': 'एडमिन डॉक्टर', 'nav.adminFacilities': 'एडमिन सुविधाएँ', 'nav.adminTests': 'एडमिन जाँच', 'nav.adminAgents': 'एडमिन एजेंट', 'nav.adminAppointments': 'एडमिन अपॉइंटमेंट', 'nav.adminReports': 'एडमिन रिपोर्ट',
    'shell.applicationAreas': 'एप्लिकेशन क्षेत्र', 'shell.workspace': 'सुरक्षित स्वास्थ्य समन्वय कार्यक्षेत्र', 'shell.fieldOperations': 'फील्ड संचालन', 'shell.fieldDescription': 'सिर्फ़ नियुक्त कलेक्शन की आवश्यक जानकारी', 'shell.phase': 'चरण 18', 'shell.openNavigation': 'नेविगेशन खोलें', 'shell.closeNavigation': 'नेविगेशन बंद करें',
    'common.signInRequired': 'साइन इन आवश्यक है', 'common.signInPatient': 'निजी मरीज़ रिकॉर्ड देखने के लिए Supabase Auth से साइन इन करें।', 'common.somethingWrong': 'कुछ गलत हुआ', 'common.loading': 'आपके रिकॉर्ड लोड हो रहे हैं…', 'common.notScheduled': 'समय निर्धारित नहीं', 'common.noRecords': 'कोई रिकॉर्ड नहीं मिला', 'common.view': 'देखें', 'common.refresh': 'रिफ्रेश', 'common.save': 'सहेजें', 'common.saving': 'सहेजा जा रहा है…', 'common.open': 'खोलें', 'common.back': 'वापस', 'common.noData': 'अभी कोई डेटा उपलब्ध नहीं है।',
    'portal.authAgentTitle': 'एजेंट साइन इन आवश्यक है', 'portal.authAgentDescription': 'नियुक्त अनुरोध देखने के लिए सत्यापित कलेक्शन-एजेंट खाते से साइन इन करें।', 'portal.authAdmin': 'एडमिन अनुमति आवश्यक है', 'portal.errorAgent': 'कलेक्शन-एजेंट कार्यक्षेत्र लोड नहीं हो सका।', 'portal.errorAdmin': 'एडमिन कार्यक्षेत्र लोड नहीं हो सका।', 'portal.errorPatient': 'यह अनुभाग लोड नहीं हो सका।', 'portal.doctorAuth': 'डॉक्टर साइन इन आवश्यक है', 'portal.doctorAuthDescription': 'क्लिनिकल कार्यक्षेत्र देखने के लिए स्वीकृत डॉक्टर खाते से साइन इन करें।', 'portal.doctorError': 'डॉक्टर कार्यक्षेत्र लोड नहीं हो सका।', 'portal.minimumNecessary': 'सिर्फ़ नियुक्त कलेक्शन के लिए आवश्यक जानकारी दिखाई जाती है। मरीज़ के मेडिकल रिकॉर्ड और असंबंधित अनुरोध निजी रहते हैं।', 'portal.locationMissing': 'स्थान उपलब्ध नहीं है',
    'portal.noAppointments': 'अभी कोई अपॉइंटमेंट नहीं', 'portal.noTests': 'अभी कोई जाँच नहीं', 'portal.noReports': 'अभी कोई रिपोर्ट उपलब्ध नहीं', 'portal.findDoctor': 'डॉक्टर खोजें', 'portal.browseFacilities': 'सुविधाएँ देखें', 'portal.today': 'आज', 'portal.upcoming': 'आगामी', 'portal.patients': 'मरीज़', 'portal.consultations': 'परामर्श', 'admin.users': 'उपयोगकर्ता', 'admin.patients': 'मरीज़', 'admin.doctors': 'डॉक्टर', 'admin.facilities': 'सुविधाएँ', 'admin.tests': 'जाँच', 'admin.agents': 'कलेक्शन एजेंट', 'admin.appointments': 'अपॉइंटमेंट', 'admin.reports': 'मेडिकल रिपोर्ट', 'admin.platformOperations': 'प्लेटफ़ॉर्म संचालन', 'admin.action': 'कार्रवाई', 'admin.loading': 'रिकॉर्ड लोड हो रहे हैं…', 'admin.noRecords': 'कोई रिकॉर्ड नहीं मिला', 'admin.viewOnly': 'केवल देखें', 'admin.verify': 'सत्यापित करें', 'admin.unverify': 'सत्यापन हटाएँ', 'admin.approve': 'स्वीकृत करें', 'admin.suspend': 'निलंबित करें', 'admin.unapprove': 'स्वीकृति हटाएँ', 'admin.activate': 'सक्रिय करें', 'admin.deactivate': 'निष्क्रिय करें',
 'ai.back': 'मरीज़ क्षेत्र पर वापस जाएँ', 'ai.badge': 'स्वास्थ्य सहायक', 'ai.title': 'स्वास्थ्य संबंधी चिंता पर बात करें।', 'ai.disclaimer': 'आप जो महसूस कर रहे हैं उसे साझा करें और प्रारंभिक जानकारी व सुरक्षित अगले कदम पाएँ। यह निदान नहीं है और योग्य चिकित्सक का विकल्प नहीं है।', 'ai.preliminary': 'केवल प्रारंभिक जानकारी', 'ai.prompt': 'आप क्या समझना चाहते हैं?', 'ai.promptDescription': 'अपने लक्षण, वे कब से हैं और किससे बेहतर या खराब होते हैं, बताएं। पासवर्ड या असंबंधित निजी जानकारी साझा न करें।', 'ai.reviewing': 'आपके संदेश की सुरक्षित समीक्षा हो रही है…', 'ai.placeholder': 'अपनी चिंता बताएं…', 'ai.ariaConcern': 'अपनी स्वास्थ्य चिंता बताएं', 'ai.ariaSend': 'संदेश भेजें', 'ai.emergencyWarning': 'आपातकाल में इस चैट का उपयोग न करें।', 'ai.safetyFirst': 'सुरक्षा पहले', 'ai.emergencyDescription': 'गंभीर लक्षणों में स्थानीय आपातकालीन सेवा को कॉल करें या निकटतम आपातकालीन विभाग जाएँ। सहायक आपात स्थिति का आकलन नहीं कर सकता।', 'ai.urgent': 'तत्काल अगला कदम', 'ai.suggested': 'सुझाया गया अगला कदम',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
export function t(locale: Locale, key: TranslationKey) { return translations[locale][key]; }
const textMap: Record<string, TranslationKey> = Object.fromEntries(Object.entries(translations.en).map(([key, value]) => [value, key])) as Record<string, TranslationKey>;
export function localize(locale: Locale, text: string) { const key = textMap[text]; return key ? t(locale, key) : text; }
