'use client';

import { useMemo, useState } from 'react';
import { Building2, ExternalLink, LocateFixed, MapPin, Phone } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

type Facility = { id: string; name: string; facility_type: string; address: string; city: string | null; state: string | null; postal_code: string | null; phone: string | null; latitude: number | null; longitude: number | null };
type Position = { latitude: number; longitude: number };
function distanceKm(a: Position, b: Position) { const earth = 6371; const rad = (value: number) => value * Math.PI / 180; const dLat = rad(b.latitude - a.latitude); const dLon = rad(b.longitude - a.longitude); const x = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(dLon / 2) ** 2; return earth * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }
function queryFor(facility: Facility) { return facility.latitude !== null && facility.longitude !== null ? `${facility.latitude},${facility.longitude}` : [facility.name, facility.address, facility.city, facility.state].filter(Boolean).join(', '); }
export function FacilityDirectory({ facilities }: { facilities: Facility[] }) { const [position, setPosition] = useState<Position | null>(null); const [locating, setLocating] = useState(false); const [locationMessage, setLocationMessage] = useState<string | null>(null); const sorted = useMemo(() => facilities.map((facility) => ({ facility, distance: position && facility.latitude !== null && facility.longitude !== null ? distanceKm(position, { latitude: facility.latitude, longitude: facility.longitude }) : null })).sort((a, b) => (a.distance ?? Number.POSITIVE_INFINITY) - (b.distance ?? Number.POSITIVE_INFINITY)), [facilities, position]); function locate() { if (!navigator.geolocation) { setLocationMessage('Location is not available in this browser.'); return; } setLocating(true); setLocationMessage(null); navigator.geolocation.getCurrentPosition((current) => { setPosition({ latitude: current.coords.latitude, longitude: current.coords.longitude }); setLocationMessage('Nearby facilities are sorted using your device location.'); setLocating(false); }, () => { setLocationMessage('Location permission was not granted. You can still use address-based map links.'); setLocating(false); }, { enableHighAccuracy: false, maximumAge: 300000, timeout: 10000 }); }
  return <><div className="mb-6 flex flex-col justify-between gap-3 rounded-2xl border border-[#dce9e8] bg-white p-4 sm:flex-row sm:items-center"><div><p className="font-semibold">Find care near you</p><p className="mt-1 text-xs leading-5 text-[#718988]">Use your device location to sort facilities. Location stays in your browser and is not sent to HealthConnect.</p>{locationMessage && <p className="mt-2 text-xs font-semibold text-[#0d766c]">{locationMessage}</p>}</div><Button variant="outline" size="sm" onClick={locate} disabled={locating}><LocateFixed size={15} />{locating ? 'Locating…' : 'Use my location'}</Button></div><div className="grid gap-4 md:grid-cols-2">{sorted.map(({ facility, distance }) => { const query = encodeURIComponent(queryFor(facility)); const maps = `https://www.google.com/maps/search/?api=1&query=${query}`; const directions = `https://www.google.com/maps/dir/?api=1&destination=${query}`; return <Card key={facility.id} className="p-6"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#fff5e7] text-[#c47643]"><Building2 size={19} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-bold">{facility.name}</h2><p className="mt-1 text-xs font-bold uppercase tracking-[.12em] text-[#8ba19f]">{facility.facility_type.replace('_', ' ')}</p></div>{distance !== null && <span className="rounded-full bg-[#e8f7f2] px-3 py-1 text-xs font-bold text-[#0d766c]">{distance < 1 ? `${Math.round(distance * 1000)} m` : `${distance.toFixed(1)} km`}</span>}</div><p className="mt-3 flex gap-2 text-sm leading-6 text-[#718988]"><MapPin className="mt-1 shrink-0" size={15} />{facility.address}, {facility.city ?? ''} {facility.state ?? ''} {facility.postal_code ?? ''}</p>{facility.phone && <p className="mt-2 flex items-center gap-2 text-sm text-[#506a6a]"><Phone size={14} />{facility.phone}</p>}<div className="mt-5 flex flex-wrap gap-2"><a href={maps} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#dce9e8] px-3 py-2 text-xs font-semibold text-[#0d766c]">View map <ExternalLink size={13} /></a><a href={directions} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#0d766c] px-3 py-2 text-xs font-semibold text-white">Directions <ExternalLink size={13} /></a></div>{facility.latitude === null || facility.longitude === null ? <p className="mt-3 text-[11px] text-[#9aafad]">Exact coordinates are not stored yet; Google Maps will search the facility address.</p> : null}</div></div></Card>; })}</div></>; }
