create type public.test_order_status as enum ('REQUESTED','CONFIRMED','SCHEDULED','COLLECTING','PROCESSING','COMPLETED','CANCELLED');
create table public.tests (id uuid primary key default gen_random_uuid(), name text not null, description text, category text, preparation_instructions text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint tests_name_nonempty check (length(trim(name)) > 0));
create table public.facility_tests (id uuid primary key default gen_random_uuid(), facility_id uuid not null references public.healthcare_facilities(id) on delete restrict, test_id uuid not null references public.tests(id) on delete restrict, price numeric(12,2) not null check (price >= 0), turnaround_hours integer check (turnaround_hours is null or turnaround_hours >= 0), facility_instructions text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (facility_id, test_id));
create table public.test_orders (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id) on delete restrict, doctor_id uuid references public.doctors(id) on delete restrict, facility_id uuid not null references public.healthcare_facilities(id) on delete restrict, test_id uuid not null references public.tests(id) on delete restrict, facility_test_id uuid not null references public.facility_tests(id) on delete restrict, status public.test_order_status not null default 'REQUESTED', scheduled_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index tests_active_idx on public.tests (is_active, name); create index facility_tests_facility_active_idx on public.facility_tests (facility_id, is_active); create index facility_tests_test_active_idx on public.facility_tests (test_id, is_active); create index test_orders_patient_created_idx on public.test_orders (patient_id, created_at desc); create index test_orders_doctor_created_idx on public.test_orders (doctor_id, created_at desc); create index test_orders_facility_status_idx on public.test_orders (facility_id, status, created_at desc);
alter table public.tests enable row level security; alter table public.facility_tests enable row level security; alter table public.test_orders enable row level security;

create or replace function public.set_test_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists tests_set_updated_at on public.tests; create trigger tests_set_updated_at before update on public.tests for each row execute function public.set_test_updated_at();
drop trigger if exists facility_tests_set_updated_at on public.facility_tests; create trigger facility_tests_set_updated_at before update on public.facility_tests for each row execute function public.set_test_updated_at();
drop trigger if exists test_orders_set_updated_at on public.test_orders; create trigger test_orders_set_updated_at before update on public.test_orders for each row execute function public.set_test_updated_at();

create or replace function public.validate_facility_test_offer() returns trigger language plpgsql security invoker set search_path = public as $$ declare v_facility_id uuid; v_test_id uuid; begin select ft.facility_id, ft.test_id into v_facility_id, v_test_id from public.facility_tests ft where ft.id = new.facility_test_id and ft.is_active = true; if v_facility_id is null or v_test_id is null then raise exception using errcode = '22023', message = 'The selected facility test offering is unavailable'; end if; if new.facility_id <> v_facility_id or new.test_id <> v_test_id then raise exception using errcode = '23514', message = 'Test order facility and test must match the selected facility offering'; end if; if not exists (select 1 from public.tests t where t.id = new.test_id and t.is_active = true) then raise exception using errcode = '22023', message = 'The selected test is inactive'; end if; if not exists (select 1 from public.healthcare_facilities f where f.id = new.facility_id and f.is_approved = true) then raise exception using errcode = '22023', message = 'The selected facility is not approved'; end if; if tg_op = 'UPDATE' and (old.patient_id <> new.patient_id or old.doctor_id is distinct from new.doctor_id or old.facility_id <> new.facility_id or old.test_id <> new.test_id or old.facility_test_id <> new.facility_test_id) then raise exception using errcode = '42501', message = 'Test order relationships are immutable'; end if; return new; end; $$;
drop trigger if exists test_orders_validate_offer on public.test_orders; create trigger test_orders_validate_offer before insert or update on public.test_orders for each row execute function public.validate_facility_test_offer();
create or replace function public.validate_test_order_transition() returns trigger language plpgsql security invoker set search_path = public as $$ begin if tg_op = 'UPDATE' and old.status <> new.status then if old.status = 'REQUESTED' and new.status not in ('CONFIRMED','CANCELLED') then raise exception using errcode = '22023', message = 'Invalid test order status transition'; end if; if old.status = 'CONFIRMED' and new.status not in ('SCHEDULED','CANCELLED') then raise exception using errcode = '22023', message = 'Invalid test order status transition'; end if; if old.status = 'SCHEDULED' and new.status not in ('COLLECTING','CANCELLED') then raise exception using errcode = '22023', message = 'Invalid test order status transition'; end if; if old.status = 'COLLECTING' and new.status not in ('PROCESSING','CANCELLED') then raise exception using errcode = '22023', message = 'Invalid test order status transition'; end if; if old.status = 'PROCESSING' and new.status not in ('COMPLETED','CANCELLED') then raise exception using errcode = '22023', message = 'Invalid test order status transition'; end if; if old.status in ('COMPLETED','CANCELLED') then raise exception using errcode = '22023', message = 'Terminal test order status cannot change'; end if; end if; return new; end; $$;
drop trigger if exists test_orders_validate_transition on public.test_orders; create trigger test_orders_validate_transition before update on public.test_orders for each row execute function public.validate_test_order_transition();

create or replace function public.create_test_order(p_patient_id uuid, p_facility_test_id uuid, p_doctor_id uuid default null, p_scheduled_at timestamptz default null, p_notes text default null) returns public.test_orders language plpgsql security definer set search_path = public as $$ declare v_order public.test_orders; v_facility_id uuid; v_test_id uuid; v_user_patient_id uuid; begin if auth.uid() is null then raise exception using errcode = '42501', message = 'Authentication required'; end if; select id into v_user_patient_id from public.patients where user_id = auth.uid(); if not public.is_doctor() and not public.is_admin() then if v_user_patient_id is null or p_patient_id <> v_user_patient_id then raise exception using errcode = '42501', message = 'Patients may order tests only for themselves'; end if; end if; if public.is_doctor() then if p_doctor_id is null or not exists (select 1 from public.doctors d where d.id = p_doctor_id and d.user_id = auth.uid() and d.approval_status = 'APPROVED') then raise exception using errcode = '42501', message = 'Only the approved ordering doctor may place this order'; end if; elsif p_doctor_id is not null and not public.is_admin() then raise exception using errcode = '42501', message = 'Doctor linkage requires an approved authenticated doctor'; end if; select ft.facility_id, ft.test_id into v_facility_id, v_test_id from public.facility_tests ft join public.healthcare_facilities f on f.id = ft.facility_id join public.tests t on t.id = ft.test_id where ft.id = p_facility_test_id and ft.is_active = true and f.is_approved = true and t.is_active = true; if v_facility_id is null then raise exception using errcode = '22023', message = 'The selected facility test offering is unavailable'; end if; insert into public.test_orders (patient_id, doctor_id, facility_id, test_id, facility_test_id, scheduled_at, notes) values (p_patient_id, p_doctor_id, v_facility_id, v_test_id, p_facility_test_id, p_scheduled_at, p_notes) returning * into v_order; return v_order; end; $$;
revoke all on function public.create_test_order(uuid, uuid, uuid, timestamptz, text) from public; grant execute on function public.create_test_order(uuid, uuid, uuid, timestamptz, text) to authenticated;
create or replace function public.update_test_order_status(p_order_id uuid, p_status public.test_order_status) returns public.test_orders language plpgsql security definer set search_path = public as $$ declare v_order public.test_orders; v_patient_user_id uuid; v_doctor_user_id uuid; begin if auth.uid() is null then raise exception using errcode = '42501', message = 'Authentication required'; end if; select * into v_order from public.test_orders where id = p_order_id; if v_order.id is null then raise exception using errcode = '22023', message = 'Test order not found'; end if; select p.user_id into v_patient_user_id from public.patients p where p.id = v_order.patient_id; select d.user_id into v_doctor_user_id from public.doctors d where d.id = v_order.doctor_id; if public.is_admin() or (v_patient_user_id = auth.uid() and p_status = 'CANCELLED') or v_doctor_user_id = auth.uid() then null; else raise exception using errcode = '42501', message = 'You are not authorized to update this test order'; end if; update public.test_orders set status = p_status where id = p_order_id returning * into v_order; return v_order; end; $$;
revoke all on function public.update_test_order_status(uuid, public.test_order_status) from public; grant execute on function public.update_test_order_status(uuid, public.test_order_status) to authenticated;

create policy tests_select_active on public.tests for select to authenticated using (is_active = true or public.is_admin()); create policy tests_insert_admin on public.tests for insert to authenticated with check (public.is_admin()); create policy tests_update_admin on public.tests for update to authenticated using (public.is_admin()) with check (public.is_admin()); create policy tests_delete_admin on public.tests for delete to authenticated using (public.is_admin());
create policy facility_tests_select_active on public.facility_tests for select to authenticated using ((is_active = true and exists (select 1 from public.healthcare_facilities f where f.id = facility_id and f.is_approved = true)) or public.is_admin()); create policy facility_tests_insert_admin on public.facility_tests for insert to authenticated with check (public.is_admin()); create policy facility_tests_update_admin on public.facility_tests for update to authenticated using (public.is_admin()) with check (public.is_admin()); create policy facility_tests_delete_admin on public.facility_tests for delete to authenticated using (public.is_admin());
create policy test_orders_select_patient on public.test_orders for select to authenticated using (exists (select 1 from public.patients p where p.id = patient_id and p.user_id = auth.uid())); create policy test_orders_select_doctor on public.test_orders for select to authenticated using (exists (select 1 from public.doctors d where d.id = doctor_id and d.user_id = auth.uid())); create policy test_orders_select_admin on public.test_orders for select to authenticated using (public.is_admin()); create policy test_orders_update_admin on public.test_orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
